[general]
name = "xz"
description = "XZ Utils"
homepage = "https://tukaani.org/xz"
licences = [
    "GPL-2.0-or-later",
    "GPL-3.0-or-later",
    "LGPL-2.1-or-later"
]

[source]
version = "5.4.6"
url = "https://github.com/tukaani-project/xz/releases/download/v5.4.6/xz-5.4.6.tar.zst"
hash = "3e9971d6d6e9d7a411b2e9414c181a5f904f860f149591b6ac55628e1aa2263d"
release = 0

[build.options]
compiler = "clang"
with_lto = true

[build]
setup = """
    %configure --disable-static --disable-rpath
"""
build = """
    %make
"""
